#
# Makeifle -- build images for chapter 1
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	kommutatorD.pdf intfun.pdf

kommutatorD.pdf:	kommutatorD.tex
	pdflatex kommutatorD.tex

intfun.pdf:	intfun.tex
	pdflatex intfun.tex
