#
# Makeifle -- build images for chapter 1
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	kommutatorD.pdf intfun.pdf ft.pdf wft.pdf lim.pdf

kommutatorD.pdf:	kommutatorD.tex
	pdflatex kommutatorD.tex

intfun.pdf:	intfun.tex
	pdflatex intfun.tex

ft.pdf:	ft.tex
	pdflatex ft.tex

wft.pdf:	wft.tex
	pdflatex wft.tex

lim.pdf:	lim.tex
	pdflatex lim.tex
