#
# Makefile -- edit images
#
all:	level1.pdf level5.pdf level1_n.pdf

level1.pdf:	level1.tex
	pdflatex level1.tex

level5.pdf:	level5.tex
	pdflatex level5.tex

level1_n.pdf:	level1_n.tex
	pdflatex level1_n.tex

