#
# Makefile.inc
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
PAPERFILES = \
	papers/part2.tex \
	papers/uebersicht.tex \
	papers/autotune/main.tex \
	papers/deconvolve/main.tex \
	papers/fpga/main.tex \
	papers/compress/main.tex \
	papers/visuell/main.tex \
	papers/complex/main.tex \
	papers/polynomials/main.tex \
	papers/gis/main.tex \
	papers/meteor/main.tex \
	papers/wwt/main.tex \
	
