#
# Makefile -- scale images
#
images:	kernel1-scaled.jpg	\
	kernel2-scaled.jpg	\
	kernel3-scaled.jpg	\
	kernelG1-scaled.jpg	\
	kernelG2-scaled.jpg	\
	kernelG3-scaled.jpg



kernel1-scaled.jpg: kernel1.jpg
	convert kernel1.jpg -scale 1600% \
		-density 300 -units PixelsPerInch kernel1-scaled.jpg

kernel2-scaled.jpg: kernel2.jpg
	convert kernel2.jpg -scale 1600% \
		-density 300 -units PixelsPerInch kernel2-scaled.jpg

kernel3-scaled.jpg: kernel3.jpg
	convert kernel3.jpg -scale 1600% \
		-density 300 -units PixelsPerInch kernel3-scaled.jpg

kernelG1-scaled.jpg: kernelG1.jpg
	convert kernelG1.jpg -scale 1600% \
		-density 300 -units PixelsPerInch kernelG1-scaled.jpg

kernelG2-scaled.jpg: kernelG2.jpg
	convert kernelG2.jpg -scale 1600% \
		-density 300 -units PixelsPerInch kernelG2-scaled.jpg

kernelG3-scaled.jpg: kernelG3.jpg
	convert kernelG3.jpg -scale 1600% \
		-density 300 -units PixelsPerInch kernelG3-scaled.jpg
