#
# Makefile.inc -- Makefile stuff needed to process the chapters
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#

CHAPTERFILES =								\
	chapters/vorwort.tex						\
	chapters/part1.tex						\
	chapters/0-einleitung/einleitung.tex				\
	chapters/1-geometrie/chapter.tex				\
	chapters/1-geometrie/vergleich.tex				\
	chapters/1-geometrie/funktionen.tex				\
	chapters/1-geometrie/hilbertraum.tex				\
	chapters/1-geometrie/rekonstruktion.tex				\
	chapters/1-geometrie/reziprok.tex				\
	chapters/1-geometrie/frames.tex					\
	chapters/1a-frames/chapter.tex					\
	chapters/1a-frames/frame.tex					\
	chapters/1a-frames/dual.tex					\
	chapters/1a-frames/ginv.tex					\
	chapters/2-fourier/chapter.tex					\
	chapters/2-fourier/l2.tex					\
	chapters/2-fourier/reihen.tex					\
	chapters/2-fourier/integral.tex					\
	chapters/2-fourier/windowed.tex					\
	chapters/3-haar/chapter.tex					\
	chapters/3-haar/stueckweise.tex					\
	chapters/3-haar/sampling.tex					\
	chapters/3-haar/dual.tex					\
	chapters/3-haar/wavelet.tex					\
	chapters/3-haar/paradox.tex					\
	chapters/4-cwt/chapter.tex					\
	chapters/4-cwt/wavelets.tex					\
	chapters/4-cwt/cwt.tex						\
	chapters/4-cwt/plancherel.tex					\
	chapters/4-cwt/umkehrformel.tex					\
	chapters/5-shannon/chapter.tex					\
	chapters/6-msa/chapter.tex					\
	chapters/6-msa/definition.tex					\
	chapters/6-msa/skalfour.tex					\
	chapters/6-msa/orthonormalisierung.tex				\
	chapters/7-algo/chapter.tex					\
	chapters/7-algo/fast.tex					\
	chapters/7-algo/rekonstruktion.tex				\
	chapters/8-kompakt/chapter.tex					\
	chapters/8-kompakt/algebra.tex					\
	chapters/8-kompakt/riesz.tex					\
	chapters/8-kompakt/partial.tex					\
	chapters/8-kompakt/ordnung.tex					\
	chapters/8-kompakt/betrag.tex					\
	chapters/8-kompakt/bedingungen.tex				\
	chapters/9-spline/chapter.tex					\
	chapters/9-spline/faltung.tex					\
	chapters/9-spline/splines.tex					\
	chapters/9-spline/wavelet.tex					\
	chapters/a-komplex/komplexezahlen.tex				\
	uebungsaufgaben/15001.tex					\
	uebungsaufgaben/15002.tex					\
	uebungsaufgaben/15003.tex					\
	uebungsaufgaben/15004.tex					\
	uebungsaufgaben/15005.tex					\
	uebungsaufgaben/15006.tex

