#
# Makefile.inc -- Makefile stuff needed to process the chapters
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#

CHAPTERFILES =								\
	chapters/vorwort.tex						\
	chapters/part1.tex						\
	chapters/einleitung.tex

