#
# Makefile.inc -- Makefile stuff needed to process the chapters
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#

CHAPTERFILES =								\
	chapters/vorwort.tex						\
	chapters/part1.tex						\
	chapters/einleitung.tex						\
	a-komplex/komplex.tex						\
	a-komplex/komplexezahlen.tex					\
	uebungsaufgaben/15001.tex					\
	uebungsaufgaben/15002.tex					\
	uebungsaufgaben/15003.tex					\
	uebungsaufgaben/15004.tex					\
	uebungsaufgaben/15005.tex					\
	uebungsaufgaben/15006.tex

