#
# Makefile -- xxx
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	xxx-handout.pdf MathSem-yyy-xxx.pdf

SOURCES = common.tex slides.tex

MathSem-yyy-xxx.pdf:	MathSem-yyy-xxx.tex $(SOURCES)
	pdflatex STAT-yyy-xxx.tex

xxx-handout.pdf:	xxx-handout.tex $(SOURCES)
	pdflatex xxx-handout.tex

